# Day 2 - Dockerfile for Vite Frontend Application

FROM node:18-alpine AS build
WORKDIR /app
COPY vite-frontend/package.json ./
RUN npm install
COPY vite-frontend/ ./
RUN npm run build

# Nginx Stage to serve production Vite build
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3000
# Override default Nginx port to 3000
RUN sed -i 's/listen       80;/listen       3000;/g' /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
